### ISSUE TITLE
mumu模拟器我试了搞不好，截图保存路径有一些问题

### ISSUE THREAD

**Issue by donxak** [LengGeng/AutoOnmyoji#1]
因为用了前端，前端那边的文件访问路径是从webgui下面找的，但是图片是写到根目录的images下的，我改了一下显示成功了。
mumu模拟器我按官网说的adb connect 127.0.0.1:7555还是不行，大佬有时间研究一下呗，感谢。
csdn回答：  有些模拟器或者真机在Windows系统下可能直接执行 adb devices 时并不能直接连接成功，这时就需要使用命令 adb connect 127.0.0.1:port 来连接。port根据使用的模拟器来填写。例如：
        1、木木： 7555
        2、夜神： 62001
        3、海马：53001
        4、逍遥：21503
        5、天天：6555
        6、雷电、genymotion、谷歌原生：5555

**Comment by donxak** [comment]
没学过python和Android所以很多看不懂emm，orz，麻烦大佬了

**Comment by LengGeng** [comment]
运行adb devices有显示吗?暂时没遇到过这种情况





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LengGeng/AutoOnmyoji"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上7:13
收件人:&nbsp;"LengGeng/AutoOnmyoji"<AutoOnmyoji@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)





 
因为用了前端，前端那边的文件访问路径是从webgui下面找的，但是图片是写到根目录的images下的，我改了一下显示成功了。
 mumu模拟器我按官网说的adb connect 127.0.0.1:7555还是不行，大佬有时间研究一下呗，感谢。
 csdn回答：  有些模拟器或者真机在Windows系统下可能直接执行 adb devices 时并不能直接连接成功，这时就需要使用命令 adb connect 127.0.0.1:port 来连接。port根据使用的模拟器来填写。例如：
 1、木木： 7555
 2、夜神： 62001
 3、海马：53001
 4、逍遥：21503
 5、天天：6555
 6、雷电、genymotion、谷歌原生：5555

**Comment by donxak** [comment]
是这样的，mumu模拟器应该是默认不能用adb devices，噗，刚试下截图成功了，（搞不懂为什么就成功了，有点尴尬。找到设备了但是目录什么的有问题，神奇的mumu模拟器，我再研究研究，以前没碰过python，有点懵哈哈

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: LengGeng<mailto:notifications@github.com>
发送时间: 2020年11月8日 19:19
收件人: LengGeng/AutoOnmyoji<mailto:AutoOnmyoji@noreply.github.com>
抄送: donxak<mailto:donxak@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)

运行adb devices有显示吗?暂时没遇到过这种情况





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LengGeng/AutoOnmyoji" <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上7:13
收件人:&nbsp;"LengGeng/AutoOnmyoji"<AutoOnmyoji@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)






因为用了前端，前端那边的文件访问路径是从webgui下面找的，但是图片是写到根目录的images下的，我改了一下显示成功了。
mumu模拟器我按官网说的adb connect 127.0.0.1:7555还是不行，大佬有时间研究一下呗，感谢。
csdn回答： 有些模拟器或者真机在Windows系统下可能直接执行 adb devices 时并不能直接连接成功，这时就需要使用命令 adb connect 127.0.0.1:port 来连接。port根据使用的模拟器来填写。例如：
1、木木： 7555
2、夜神： 62001
3、海马：53001
4、逍遥：21503
5、天天：6555
6、雷电、genymotion、谷歌原生：5555

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by LengGeng** [comment]
其实这个前端的截图还是有问题的,
前端的截图暂时是独立的,如果进行截图的设备有任务正在执行并调用了截图功能,这时候前端再调用可能会产生冲突,执行的任务可能会直接报错终止





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LengGeng/AutoOnmyoji"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上7:35
收件人:&nbsp;"LengGeng/AutoOnmyoji"<AutoOnmyoji@noreply.github.com&gt;;
抄送:&nbsp;"冷羹"<906506482@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)





 是这样的，mumu模拟器应该是默认不能用adb devices，噗，刚试下截图成功了，（搞不懂为什么就成功了，有点尴尬。找到设备了但是目录什么的有问题，神奇的mumu模拟器，我再研究研究，以前没碰过python，有点懵哈哈 
 
 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;应用 
 
 发件人: LengGeng<mailto:notifications@github.com&gt; 
 发送时间: 2020年11月8日 19:19 
 收件人: LengGeng/AutoOnmyoji<mailto:AutoOnmyoji@noreply.github.com&gt; 
 抄送: donxak<mailto:donxak@outlook.com&gt;; Author<mailto:author@noreply.github.com&gt; 
 主题: Re: [LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1) 
 
 运行adb devices有显示吗?暂时没遇到过这种情况 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "LengGeng/AutoOnmyoji" <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月8日(星期天) 晚上7:13 
 收件人:&amp;nbsp;"LengGeng/AutoOnmyoji"<AutoOnmyoji@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1) 
 
 
 
 
 
 
 因为用了前端，前端那边的文件访问路径是从webgui下面找的，但是图片是写到根目录的images下的，我改了一下显示成功了。 
 mumu模拟器我按官网说的adb connect 127.0.0.1:7555还是不行，大佬有时间研究一下呗，感谢。 
 csdn回答： 有些模拟器或者真机在Windows系统下可能直接执行 adb devices 时并不能直接连接成功，这时就需要使用命令 adb connect 127.0.0.1:port 来连接。port根据使用的模拟器来填写。例如： 
 1、木木： 7555 
 2、夜神： 62001 
 3、海马：53001 
 4、逍遥：21503 
 5、天天：6555 
 6、雷电、genymotion、谷歌原生：5555 
 
 ― 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―

**Comment by donxak** [comment]
PS E:\yys_test\******> python .\run.py
当前设备列表
序号   设备编号           类型
0      127.0.0.1:7555   device
请输入要连接的设备序号：0
您选择的设备是: 127.0.0.1:7555
功能列表
序号   功能             对应函数
0    x               x
1    x                x
2    x              x
3   x             x
4    x              x
5    x              x
6    x          x
7    x              x
请为设备 127.0.0.1:7555 配置功能1
您选择的是 挑战 功能
挑战的次数2
正在等待所有子进程完成
[WinError 267] 目录名称无效。: 'log\\127.0.0.1:7555'
所有子流程都已完成
我晚点找找别的模拟器试试，蓝叠只用点个配置就行了，能运行，但是运行起来风扇有点噪，感觉还是mumu这边有啥不一样

**Comment by LengGeng** [comment]
这也是个BUG,哈哈哈,下次改,路径中不能有":"(冒号)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LengGeng/AutoOnmyoji"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上8:44
收件人:&nbsp;"LengGeng/AutoOnmyoji"<AutoOnmyoji@noreply.github.com&gt;;
抄送:&nbsp;"冷羹"<906506482@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)





 
PS E:\yys_test******&gt; python .\run.py
 当前设备列表
 序号   设备编号           类型
 0      127.0.0.1:7555   device
 请输入要连接的设备序号：0
 您选择的设备是: 127.0.0.1:7555
 功能列表
 序号   功能             对应函数
 0    x               x
 1    x                x
 2    x              x
 3   x             x
 4    x              x
 5    x              x
 6    x          x
 7    x              x
 请为设备 127.0.0.1:7555 配置功能1
 您选择的是 挑战 功能
 挑战的次数2
 正在等待所有子进程完成
 [WinError 267] 目录名称无效。: 'log\127.0.0.1:7555'
 所有子流程都已完成
 我晚点找找别的模拟器试试，蓝叠只用点个配置就行了，能运行，但是运行起来风扇有点噪，感觉还是mumu这边有啥不一样

**Comment by donxak** [comment]
上课半天找不到在哪改创建的日志文件夹的名字，回来之后灵光一闪，把logger.py剪切出来了，发现是我一直没打开看的Onmyo....文件调用的，往里边插了个.replace(":","_")就能用了————哭唧唧，我是真的菜

**Comment by LengGeng** [comment]
是的，当时没有做路径的检查

---原始邮件---
发件人: &quot;donxak&quot;<notifications@github.com&gt;
发送时间: 2020年11月8日 22:30:27
收件人: &quot;LengGeng/AutoOnmyoji&quot;<AutoOnmyoji@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;LengGeng&quot;<906506482@qq.com&gt;;
主题: Re: [LengGeng/AutoOnmyoji] mumu模拟器我试了搞不好，截图保存路径有一些问题 (#1)




 
上课半天找不到在哪改创建的日志文件夹的名字，回来之后灵光一闪，把logger.py剪切出来了，发现是我一直没打开看的Onmyo....文件调用的，往里边插了个.replace(":","_")就能用了————哭唧唧，我是真的菜
 
&mdash;

**Comment by LengGeng** [comment]
该问题已修复(07dcd9be)
